spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    url: jdbc:sqlserver://database-1.cxmk4gnjrz7s.us-east-1.rds.amazonaws.com:1433;databaseName=Cloud_Vendor;encrypt=true;trustServerCertificate=true;
    username: sri
    password: Sreekanth7
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    hibernate:
      ddl-auto: create
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL57Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
